### PR TITLE
Update HOL step-by-step - Building the business migration case with L…

### PR DESCRIPTION
**Pull request by sqllocks**
…inux and OSS DB to Azure.md

Added information about potential transient error and how to resolve the problem.

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann @sar2olson @v-denisea 
Hey guys!  I had a question about the PR so I didn't merge it or close the issue.  It looks like the instructions added are duplicates of what's above.  If you look at lines 249 & 255, they look the same to me.  Are there TWO potential errors they're addressing, or did the same instructions get added twice?

**Comment by sqllocks** [comment]
> @crpietschmann @sar2olson @v-denisea Hey guys! I had a question about the PR so I didn't merge it or close the issue. It looks like the instructions added are duplicates of what's above. If you look at lines 249 & 255, they look the same to me. Are there TWO potential errors they're addressing, or did the same instructions get added twice?

Hi Dawnmarie,

This has been fixed and the PR should be ready to go.

**Comment by sqllocks** [comment]
@DawnmarieDesJardins  The PR is ready to be merged.

**Comment by v-denisea** [comment]
Per Dawn review ok to merge

**Pull request merged**
